name: Run Zeitzuordnung and upload CSV asset
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * 1'
jobs:
  build-and-publish-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: echo "DATE=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Run Go program
        uses: actions/setup-go@v2
      - run: echo "TAG_NAME=$(go run zeitzuordnung.go)" >> $GITHUB_ENV
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: |
            *.csv